version: '3.7'

services:

  tomcat:
    image: oleg2019/tomcat
    container_name: tomcat
    ports:
      - "8080:8080"
    networks:
      - backend

  db:
    image: mariadb 
    container_name: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - backend
    ports:
      - 3306:3306
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: fias 
      MYSQL_USER: fias
      MYSQL_PASSWORD: fias123

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    networks:
      - backend
    ports:
      - 8090:8080

networks:
     backend:
        driver: "bridge"
